services:
  mysql:
    build: ./srcs/mysql
    image: mysql
    container_name: mysql
    env_file: 
      - ./srcs/.env
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - net

  wordpress:
    build: ./srcs/wordpress
    image: wordpress
    container_name: wordpress
    env_file: 
      - ./srcs/.env
    ports:
      - 9000:9000
    volumes:
      - wordpress:/var/www/html
      - mysql_data:/var/lib/mysql
    depends_on:
      - mysql
    restart: always
    networks:
      - net

  nginx:
    build: ./srcs/nginx
    image: nginx
    container_name: nginx
    env_file: 
      - ./srcs/.env
    ports:
      - 80:80
      - 443:443
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    restart: always
    networks:
      - net

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /Users/btammara/volumes/wordpress
      o: bind
  mysql_data:
    driver: local
    driver_opts:
      type: none
      device: /Users/btammara/volumes/mysql_data
      o: bind

networks:
  net:
    driver: bridge
      