services:
  mysql:
    build: ./srcs/mysql
    env_file: 
      - ./srcs/.env
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - net

  wordpress:
    build: ./srcs/wordpress
    env_file: 
      - ./srcs/.env
    ports:
      - 9000:9000
    volumes:
      - wordpress:/var/www/html
      - mysql_data:/var/lib/mysql
    depends_on:
      - mysql
    restart: always
    networks:
      - net

  nginx:
    build: ./srcs/nginx
    env_file: 
      - ./srcs/.env
    ports:
      - 80:80
      - 443:443
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    restart: always
    networks:
      - net

volumes:
  wordpress:
  mysql_data:

networks:
  net:
    driver: bridge
      