services:
  services:
    build: ./srcs/wordpress
    ports:
      - 3306:3306
      - 9000:9000
    volumes:
      - wordpress:/var/www/html
  nginx:
    build: ./srcs/nginx
    ports:
      - 80:80
      - 443:443
    links:
      - services
    volumes:
      - wordpress:/var/www/html
volumes:
  wordpress:
      