services:
  mysql:
    build: ./srcs/mysql
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
  wordpress:
    build: ./srcs/wordpress
    ports:
      - 9000:9000
    volumes:
      - wordpress:/var/www/html
      - mysql_data:/var/lib/mysql
    depends_on:
      - mysql
    restart: always
  phpmyadmin:
    build: ./srcs/phpmyadmin
    # ports:
    #   - 9000:9000
    volumes:
    #   - wordpress:/var/www/html
      - mysql_data:/var/lib/mysql
    depends_on:
      - mysql
    links:
      - wordpress
    restart: always
  nginx:
    build: ./srcs/nginx
    ports:
      - 80:80
      - 443:443
    links:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    restart: always
volumes:
  wordpress:
  mysql_data:
      